# Generated by Django 5.2.5 on 2025-11-06 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='denuncia',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Denuncia', 'verbose_name_plural': 'Denuncias'},
        ),
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'ordering': ['-fecha_sincronizacion'], 'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='historialdenuncia',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial de Denuncia', 'verbose_name_plural': 'Historial de Denuncias'},
        ),
        migrations.AlterModelOptions(
            name='logactividad',
            options={'ordering': ['-fecha'], 'verbose_name': 'Log de Actividad', 'verbose_name_plural': 'Logs de Actividad'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='observacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Observación', 'verbose_name_plural': 'Observaciones'},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterModelOptions(
            name='tokenrecuperacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Token de Recuperación', 'verbose_name_plural': 'Tokens de Recuperación'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='denuncia',
            name='evidencia',
            field=models.FileField(blank=True, help_text='Archivo de evidencia (imagen o video)', null=True, upload_to='evidencias/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la categoría', null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='Nombre de la categoría', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(help_text='Identificador único (ej: flora, fauna, contaminacion)', unique=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría de la denuncia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='appProyecto.categoria'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada del problema'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelta', 'Resuelta'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Estado actual de la denuncia', max_length=50),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='evidencia_url',
            field=models.CharField(blank=True, help_text='URL alternativa de evidencia', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', help_text='Nivel de prioridad', max_length=20),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='titulo',
            field=models.CharField(help_text='Título breve de la denuncia', max_length=150),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Ubicación GPS del incidente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='appProyecto.ubicacion'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que creó la denuncia', on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='fecha_sincronizacion',
            field=models.DateTimeField(auto_now=True, help_text='Última sincronización'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='identificador',
            field=models.CharField(help_text='Identificador único (serial/MAC)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(choices=[('camara', 'Cámara'), ('dron', 'Dron'), ('sensor', 'Sensor'), ('estacion_clima', 'Estación Climática')], help_text='Tipo de dispositivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='ultima_ubicacion',
            field=models.ForeignKey(blank=True, help_text='Última ubicación registrada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='appProyecto.ubicacion'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario responsable', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialdenuncia',
            name='cambio_descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del cambio', null=True),
        ),
        migrations.AlterField(
            model_name='historialdenuncia',
            name='denuncia',
            field=models.ForeignKey(help_text='Denuncia afectada', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='appProyecto.denuncia'),
        ),
        migrations.AlterField(
            model_name='historialdenuncia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de la acción'),
        ),
        migrations.AlterField(
            model_name='historialdenuncia',
            name='tipo_accion',
            field=models.CharField(choices=[('creacion', 'Creación'), ('edicion', 'Edición'), ('cambio_estado', 'Cambio de Estado'), ('comentario', 'Comentario'), ('asignacion', 'Asignación')], help_text='Tipo de acción realizada', max_length=50),
        ),
        migrations.AlterField(
            model_name='historialdenuncia',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_denuncias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='accion',
            field=models.CharField(help_text='Descripción de la acción realizada', max_length=255),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la acción'),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='ip_origen',
            field=models.CharField(blank=True, help_text='Dirección IP del usuario', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_actividad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.TextField(help_text='Contenido del mensaje'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(help_text='Usuario que envía el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False, help_text='Indica si el mensaje fue leído'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='receptor',
            field=models.ForeignKey(help_text='Usuario que recibe el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría de la observación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones', to='appProyecto.categoria'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='imagen_url',
            field=models.CharField(blank=True, help_text='URL de imagen', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='titulo',
            field=models.CharField(help_text='Título de la observación', max_length=150),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Ubicación de la observación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones', to='appProyecto.ubicacion'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que realizó la observación', on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='archivo_url',
            field=models.CharField(blank=True, help_text='URL del archivo PDF generado', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del reporte', null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de generación'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='titulo',
            field=models.CharField(help_text='Título del reporte', max_length=150),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que generó el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tokenrecuperacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del token'),
        ),
        migrations.AlterField(
            model_name='tokenrecuperacion',
            name='fecha_expiracion',
            field=models.DateTimeField(help_text='Fecha de expiración (24h desde creación)'),
        ),
        migrations.AlterField(
            model_name='tokenrecuperacion',
            name='token',
            field=models.CharField(help_text='Token único generado', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenrecuperacion',
            name='usado',
            field=models.BooleanField(default=False, help_text='Indica si el token ya fue usado'),
        ),
        migrations.AlterField(
            model_name='tokenrecuperacion',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que solicitó recuperación', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='altitud',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altitud en metros sobre el nivel del mar', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción textual del lugar', null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de registro de la ubicación'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='latitud',
            field=models.DecimalField(decimal_places=8, help_text='Latitud GPS', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='longitud',
            field=models.DecimalField(decimal_places=8, help_text='Longitud GPS', max_digits=11),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la cuenta está activa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario Público'), ('revisor', 'Revisor'), ('admin', 'Administrador')], default='usuario', help_text='Rol del usuario en el sistema', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True),
        ),
    ]
